// Help and markdown rendering for the dynamic tool commands.
import { Access, toolParams } from './catalog.js';
import { globalUsage } from './usage.js';
import { ALLOW_DESTRUCTIVE_ENV } from './toolrun.js';

export function summaryLine(desc, max) {
  desc = (desc ?? '').trim();
  const i = desc.indexOf('\n\n');
  if (i > 0) desc = desc.slice(0, i);
  desc = desc.split(/\s+/).filter(Boolean).join(' ');
  return desc.length > max ? desc.slice(0, max) + '…' : desc;
}

function typeHint(p) {
  if (p.enum?.length) return p.enum.join('|');
  if (p.type === 'array') return (p.item_type || 'string') + ',...';
  if (p.type === 'object') return 'json';
  return p.type;
}

export function toolUsageLine(t) {
  let b = 'fairmind ' + t.command;
  for (const p of toolParams(t)) {
    let arg = ' --' + p.flag + (p.type !== 'boolean' ? ' <' + typeHint(p) + '>' : '');
    if (!p.required) arg = ' [' + arg.trim() + ']';
    b += arg;
  }
  if (t.access !== Access.READ) b += ' --yes';
  return b;
}

export function toolUsage(t) {
  let b = `Usage: ${toolUsageLine(t)}\n\nFairMind tool ${t.name} — access: ${t.access}\n\n${(t.description ?? '').trim()}\n`;
  const ps = toolParams(t);
  if (ps.length) {
    b += '\nParameters:\n';
    for (const p of ps) {
      b += `  --${p.flag} <${typeHint(p)}>${p.required ? ' (required)' : ''}\n`;
      if (p.description) b += `      ${summaryLine(p.description, 300)}\n`;
    }
  }
  b += `
Notes:
  - Required parameters can also be given positionally, in the order above.
  - --project / project_id, git_remote and agent are filled from the resolved context when omitted.
  - Text values: @file reads a file, @- reads stdin, @@x is a literal "@x".
  - --args-json '{"key": value}' passes raw arguments (merged under explicit flags).
  - --dry-run shows the arguments without calling FairMind.
`;
  if (t.access !== Access.READ) b += '  - This tool WRITES to FairMind: it requires --yes.\n';
  if (t.access === Access.DESTRUCTIVE || t.access === Access.SENSITIVE) b += `  - ${t.access} tool: also requires ${ALLOW_DESTRUCTIVE_ENV}=1, set by a human.\n`;
  return b + globalUsage;
}

export function namespaceUsage(tools, ns) {
  let b = `Usage: fairmind ${ns} <command> [flags]\n\nCommands (from the live FairMind catalog):\n`;
  for (const t of tools) {
    if (t.namespace !== ns) continue;
    const sub = t.command.slice(ns.length + 1);
    const tag = t.access !== Access.READ ? ` [${t.access}]` : '';
    b += `  ${sub.padEnd(36)} ${summaryLine(t.description, 90)}${tag}\n`;
  }
  return b + `\nRun \`fairmind ${ns} <command> --help\` for parameters.\n`;
}

export function toolsMarkdown(tools, now) {
  const counts = {}; const byNS = {};
  for (const t of tools) { counts[t.access] = (counts[t.access] ?? 0) + 1; (byNS[t.namespace] ??= []).push(t); }
  let b = '# FairMind tools reference\n\n';
  b += `Generated by \`fairmind tools docs\` on ${now.toISOString().slice(0, 10)} from the live catalog: ${tools.length} tools `;
  b += `(${counts.read ?? 0} read, ${counts.write ?? 0} write, ${counts.destructive ?? 0} destructive, ${counts.sensitive ?? 0} sensitive).\n`;
  b += `
Every tool is a CLI command: \`fairmind <namespace> <command> [--flag value ...] --json\`.

- Required parameters can be given positionally, in the order listed.
- \`project\` / \`project_id\` default to the folder's FairMind project and accept its name; \`git_remote\` defaults to the local remote; \`agent\` defaults to the configured agent name (e.g. github-copilot).
- Text values accept \`@file\` (read from a file) and \`@-\` (stdin), e.g. \`--journal-content @journal.md\`.
- **write** tools need \`--yes\` (preview with \`--dry-run\`). Only use them when the user asked for that change.
- **destructive / sensitive** tools are for humans only: they also need \`${ALLOW_DESTRUCTIVE_ENV}=1\`. Never set it yourself.
- \`fairmind <namespace> <command> --help\` shows the same information; \`fairmind tools list --json\` lists everything.
`;
  for (const ns of Object.keys(byNS).sort()) {
    b += `\n## ${ns[0].toUpperCase()}${ns.slice(1)}\n`;
    for (const t of byNS[ns]) {
      b += `\n### \`fairmind ${t.command}\` — ${t.access}\n\nTool \`${t.name}\`. ${summaryLine(t.description, 400)}\n`;
      const ps = toolParams(t);
      if (!ps.length) { b += '\nNo parameters.\n'; continue; }
      b += '\n| Flag | Type | Required | Description |\n|---|---|---|---|\n';
      for (const p of ps) {
        const desc = summaryLine(p.description, 220).replace(/\|/g, '\\|');
        b += `| \`--${p.flag}\` | ${typeHint(p).replace(/\|/g, '\\|')} | ${p.required ? 'yes' : ''} | ${desc} |\n`;
      }
    }
  }
  return b;
}
