#!/usr/bin/env python3
"""
sync_copilot_agents.py — generate what GitHub Copilot CLI loads instead of the
Claude Code agent files, so both hosts run the same agents.

WHY. The agents in `agents/` pin a Claude model (`model: claude-opus-4-8`,
`model: claude-sonnet-5`). Under Claude Code that is a deliberate choice; under
Copilot CLI a model the account does not offer means the sub-agent never starts.
Copilot reads `.github/plugin/plugin.json` BEFORE `.claude-plugin/plugin.json`
(Claude Code reads only the latter), and a manifest may point `agents` at another
directory. So:

  .github/plugin/plugin.json   = .claude-plugin/plugin.json + "agents": "./copilot/agents/"
  copilot/agents/<file>.md     = agents/<file>.md with `model: inherit` in its frontmatter

`model: inherit` runs the sub-agent on the session's own model, which Copilot
supports. The description loses its `<example>` blocks and is written as a
quoted YAML string: Copilot parses frontmatter strictly and silently drops an
agent whose plain-scalar description holds a `: ` (every `Context: … user: …`
example does), where Claude Code is lenient (measured on Copilot CLI 1.0.90 —
four of the six agents were missing from its sub-agent tool). Nothing else in
an agent changes.

USAGE
    python3 scripts/sync_copilot_agents.py           # (re)generate
    python3 scripts/sync_copilot_agents.py --check   # exit 1 when out of date

Run it after any change to `agents/` or to `.claude-plugin/plugin.json`.
"""

from __future__ import annotations

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_AGENTS = os.path.join(ROOT, "agents")
DST_AGENTS = os.path.join(ROOT, "copilot", "agents")
SRC_MANIFEST = os.path.join(ROOT, ".claude-plugin", "plugin.json")
DST_MANIFEST = os.path.join(ROOT, ".github", "plugin", "plugin.json")

_GENERATED = "# GENERATED by scripts/sync_copilot_agents.py from agents/{name} — edit that file, not this one."


_EXAMPLE = re.compile(r"\s*<example>.*?</example>", re.S)


def _strip_examples(line):
    """`description:` without its `<example>` blocks, the `Examples:` lead-in
    and list dashes they leave dangling, literal `\\n` escapes and any other tag,
    as a double-quoted YAML scalar (a JSON string is one)."""
    text = line[len("description:"):].strip()
    text = _EXAMPLE.sub("", text)
    text = re.sub(r"\\n", " ", text)
    text = re.sub(r"<[^>]*>", "", text)
    text = re.sub(r"\s*Examples?:[\s-]*$", "", text)
    text = re.sub(r"\s{2,}", " ", text).strip()
    return "description: " + json.dumps(text, ensure_ascii=False)


def copilot_agent(text, name):
    """The agent with its frontmatter `model:` set to `inherit` and a generated
    marker. Refuses a file without frontmatter rather than guessing."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"agents/{name} has no frontmatter")
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        raise ValueError(f"agents/{name} has an unterminated frontmatter")
    head = [_strip_examples(line) if line.startswith("description:") else line
            for line in lines[1:end] if not line.startswith("model:")]
    head.append("model: inherit")
    head.append(_GENERATED.format(name=name))
    return "\n".join(["---"] + head + lines[end:])


def copilot_manifest(text):
    manifest = json.loads(text)
    manifest["agents"] = "./copilot/agents/"
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def expected():
    files = {}
    for name in sorted(os.listdir(SRC_AGENTS)):
        if name.endswith(".md"):
            with open(os.path.join(SRC_AGENTS, name), encoding="utf-8") as handle:
                files[os.path.join(DST_AGENTS, name)] = copilot_agent(handle.read(), name)
    with open(SRC_MANIFEST, encoding="utf-8") as handle:
        files[DST_MANIFEST] = copilot_manifest(handle.read())
    return files


def _read(path):
    try:
        with open(path, encoding="utf-8") as handle:
            return handle.read()
    except OSError:
        return None


def main(argv):
    files = expected()
    stale = [path for path, text in files.items() if _read(path) != text]
    extra = [os.path.join(DST_AGENTS, name) for name in
             (os.listdir(DST_AGENTS) if os.path.isdir(DST_AGENTS) else [])
             if os.path.join(DST_AGENTS, name) not in files]
    if "--check" in argv:
        for path in stale + extra:
            print(f"out of date: {os.path.relpath(path, ROOT)}")
        if stale or extra:
            print("run: python3 scripts/sync_copilot_agents.py")
            return 1
        return 0
    for path in stale:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(files[path])
        print(f"wrote {os.path.relpath(path, ROOT)}")
    for path in extra:
        os.remove(path)
        print(f"removed {os.path.relpath(path, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
